version: '3.9'

services:
  line_provider:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - DATABASE_URL=postgresql://pweb:pweb@db2:5432/fast_api_tasker
    depends_on:
      - db
    networks:
      - app_network

  db:
    image: postgres
    container_name: db
    environment:
      POSTGRES_USER: pweb
      POSTGRES_PASSWORD: pweb
      POSTGRES_DB: fast_api_tasker
    ports:
      - "5432:5432"
    networks:
      - app_network

networks:
  app_network:
    driver: bridge